### ISSUE TITLE
Does contributing to OSS count? 

### ISSUE THREAD

**Issue by safwansamsudeen** [hackclub/arcade-constitution#2]
There's this project - frappe/gantt - that I've worked on a lot in the past. There are many new issues and I'd like to work and publish a new version. I will be doing this on my own, basically (the Frappe org seems to have Gantt on unmaintained) - would this count towards Arcade?

Thanks!

**Comment by zachlatta** [comment]
Yes, this would absolutely count!

It meets the following requirements:

* A project is a self-directed creative effort toward an output that other people can meaningfully experience.
* The journey of each project must be shared in a public git repository, with at least one update committed per hour logged.

It also feels like it meets these "grey area" requirements:

>     How technical is this project?
>     Is this person pushing themselves?
>     Does this project feel wholesome?
>     Is this a highly self-directed project?
>     Is this a good story?
>     Am I amazed?
