### ISSUE TITLE
Question about active learning vs passive learning (originally a question about music)

### ISSUE THREAD

**Issue by krishnayah** [hackclub/arcade-constitution#6]
EXPANDED BELOW -- Original question: Does learning a song cover on guitar count as long as my commits are documenting my progress?

**Comment by krishnayah** [comment]
To add on to above, on one hand learning a song cover is active learning– you're actively playing along and trying to figure things out as you go. On the other hand, I'm not sure how this is covered by the constitution. 

Could there be a clause in the constitution that supports active learning (building alongside something, like creating models from a blender tutorial, rather than idly watching a video?)

**Comment by DillonB07** [comment]
Hi!
Active learning is ok if what you produce is different from what is taught in the tutorial & you specify where it's from.
This is already covered here:
> Tutorial projects that are 1:1 copies of the tutorial do not count. If you're doing a tutorial, you need to "make it your own" in some way
