### ISSUE TITLE
CAD file size problems + alternate source control nature

### ISSUE THREAD

**Issue by chardynamics** [hackclub/arcade-constitution#7]
Hello,

There has been some questions raised at the CAD proof questions articulated in this document. Specifically, about uploading source files, .step and .stl files. For some users, these can easily be gargantuan, even when using git lfs (only 1gb limit). As such, their sessions may be denied.

However, there is an easy solution to most of these problems. Many CAD sources host any projects using their software on their servers, which means the burden to provide such files is lessened. Also, for example OnShape has a source control system with commits/changes, etc.

Is it possible for the constitution be amended to allow these methods of open source? Or at least be eased? Any change would be preferrable. Thanks!

**Comment by polytroper** [comment]
I agree the current process is a pain in the ass… unfortunately I think we just have to cope with it for the remainder of Arcade. There's just a bunch of stuff internally built around git specifically. But low-quality STL exports, or just exports of individual parts, are fine. If a file is truly too large, include a screenshot and a comment about why no STL
